config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'home#home', as: :home
  resources :companies

  root 'home#home'

end

app/models/company.rb
class Company < ActiveRecord::Base

  # Scopes
  scope :alphabetical,  -> { order('name') }

  # def self.search(search)
  #   if search
  #     find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  #   else
  #     # find(:all)
  #   end
  # end

  def get_weeks
    weeks = [-52, -39, -26, -13, -4, -3, -2, -1]
  end

  def get_exact_price(ratio, curr_price)
    f = curr_price * (100.0 + ratio) / 100.0
    f.round(2)
  end

  def get_weeks_prices
    pc = price_current
    prices = [get_exact_price(pr52, pc),
             get_exact_price(pr39, pc),
           get_exact_price(pr26, pc),
         get_exact_price(pr13, pc),
       get_exact_price(pr04, pc),
     get_exact_price(pr03, pc),
   get_exact_price(pr02, pc),
   get_exact_price(pr01, pc),]
  end

  def is_variable_stock?
    ratios = [pr52,pr39,pr26,pr13,pr04,pr03,pr02,pr01]
    diff_sum = 0
    for i in 0...7
      diff_sum += (ratios[i] - ratios[i+1]).abs
    end
    result = diff_sum > 8
  end

  def is_worse_stock?
    result = (per_FY1 + per_FY2 + per_LFY) / 3.0
    result.round(2)
  end

  def is_moment_down_stock?
    ratios = [pr52,pr39,pr26,pr13,pr04,pr03,pr02,pr01]
    b1 = pr52 < 0 && pr39 < 0 && pr26 < 0 && pr13 < 0
    b2 = pr39 < 0 && pr26 < 0 && pr13 < 0 && pr04 < 0
    b3 = pr26 < 0 && pr13 < 0 && pr04 < 0 && pr03 < 0
    b4 = pr13 < 0 && pr04 < 0 && pr03 < 0 && pr02 < 0
    b5 = pr04 < 0 && pr03 < 0 && pr02 < 0 && pr01 < 0
    result = b1 || b2 || b3 || b4 || b5
  end

  def is_moment_up_stock?
    ratios = [pr52,pr39,pr26,pr13,pr04,pr03,pr02,pr01]
    b1 = pr52 > 0 && pr39 > 0 && pr26 > 0 && pr13 > 0
    b2 = pr39 > 0 && pr26 > 0 && pr13 > 0 && pr04 > 0
    b3 = pr26 > 0 && pr13 > 0 && pr04 > 0 && pr03 > 0
    b4 = pr13 > 0 && pr04 > 0 && pr03 > 0 && pr02 > 0
    b5 = pr04 > 0 && pr03 > 0 && pr02 > 0 && pr01 > 0
    result = b1 || b2 || b3 || b4 || b5
  end

  def find_stock_type
    if is_variable_stock?
      result = "Variable Stock"
    elsif is_worse_stock?
      result = "Worse Stock"
    elsif is_moment_up_stock?
      result = "Moment Up Stock"
    elsif is_moment_down_stock?
      result = "Moment Down Stock"
    else
      result = "Other"
    end
    result
  end

  def find_action
    if is_variable_stock?
      result = "Variable Stock"
    elsif is_worse_stock?
      result = "Worse Stock"
    elsif is_moment_up_stock?
      result = "Moment Up Stock"
    elsif is_moment_down_stock?
      result = "Moment Down Stock"
    else
      result = "Other"
    end
    result
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    # @companies = Company.alphabetical.paginate(page: params[:page]).per_page(20)
    if params[:search]
      @companies = Company.where("symbol LIKE ?", "#{params[:search]}").paginate(page: params[:page]).per_page(20)
      # @companies = Company.find(:all, :conditions => ['name LIKE ?', "%#{params[:search]}%"])
    else
      @companies = Company.alphabetical.paginate(page: params[:page]).per_page(20)
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    xs = @company.get_weeks
    ys = @company.get_weeks_prices
    xs_labels = []
    for x in xs
      xs_labels << x.to_s
    end
    data = xs.zip(ys).flatten
    @line_chart = Gchart.line(
                  # :data => [@company.get_weeks, @company.get_weeks_prices]
                  :size => '550x350',
                  :title => "Price Plot",
                  :axis_with_labels => ['y', 'x'],
                  # :axis_lables => [[xs.join("|")]],
                  :axis_lables => [xs_labels],
                  :data => ys
                  )
    # For analysis
    @stock_type = @company.find_stock_type
    @choice = @company.find_action
  end


  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :symbol, :pr01, :pr02, :pr04, :pr13, :pr26, :pr03, :pr39, :pr52, :pr_year_to_date, :price_current, :warranted_price, :per_FY1, :per_FY2, :per_LFY)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :pr01 %><br>
    <%= f.text_field :pr01 %>
  </div>
  <div class="field">
    <%= f.label :pr02 %><br>
    <%= f.text_field :pr02 %>
  </div>
  <div class="field">
    <%= f.label :pr04 %><br>
    <%= f.text_field :pr04 %>
  </div>
  <div class="field">
    <%= f.label :pr13 %><br>
    <%= f.text_field :pr13 %>
  </div>
  <div class="field">
    <%= f.label :pr26 %><br>
    <%= f.text_field :pr26 %>
  </div>
  <div class="field">
    <%= f.label :pr03 %><br>
    <%= f.text_field :pr03 %>
  </div>
  <div class="field">
    <%= f.label :pr39 %><br>
    <%= f.text_field :pr39 %>
  </div>
  <div class="field">
    <%= f.label :pr52 %><br>
    <%= f.text_field :pr52 %>
  </div>
  <div class="field">
    <%= f.label :pr_year_to_date %><br>
    <%= f.number_field :pr_year_to_date %>
  </div>
  <div class="field">
    <%= f.label :price_current %><br>
    <%= f.text_field :price_current %>
  </div>
  <div class="field">
    <%= f.label :warranted_price %><br>
    <%= f.text_field :warranted_price %>
  </div>
  <div class="field">
    <%= f.label :per_FY1 %><br>
    <%= f.text_field :per_FY1 %>
  </div>
  <div class="field">
    <%= f.label :per_FY2 %><br>
    <%= f.text_field :per_FY2 %>
  </div>
  <div class="field">
    <%= f.label :per_LFY %><br>
    <%= f.text_field :per_LFY %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">MasterList of Companies</h1>
<br>

<div id="search-form" align="center">
<%= form_tag companies_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
</div>

<br>
<br>

<div class="container">

  <table class="table table-hover">
    <thead>
      <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Price Return year to date</th>
      <th>Current Price</th>
      <th>Warranted price</th>
      <th>Price Earning Ratio LFY</th>
      </tr>
    </thead>
    <tbody>

      <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company_path(company) %></td>
        <td><%= company.symbol %></td>
        <td><%= company.pr_year_to_date %></td>
        <td><%= company.price_current %></td>
        <td><%= company.warranted_price %></td>
        <td><%= company.per_LFY %></td>
      </tr>
    <% end %>

    </tbody>
  </table>
</div>

<span class="smtext" align="center">
<%= will_paginate @companies, previous_label:"Previous&nbsp;",next_label:"&nbsp;Next" %>
</span>

app/views/companies/new.html.erb
<h1>New Company</h1>


<%= form_for @company, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :symbol %>
  <%= f.submit "Create" %>
<% end %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2><%= @company.name %>   <small><%= @company.symbol %></small></h2>
  <br>
  <table class="table table-hover">
    <thead>
      <tr>
      <th>Price return (1 week ago)</th>
      <th>Price return (2 weeks ago)</th>
      <th>Price return (3 weeks ago)</th>
      <th>Price return (4 weeks ago)</th>
      <th>Price return (13 weeks ago)</th>
      <th>Price return (26 weeks ago)</th>
      <th>Price return (39 weeks ago)</th>
      <th>Price return (52 weeks ago)</th>
      <th>Price return (year to date)</th>
      <th>Price current</th>
      <th>Warranted price</th>
      <th>Price Earning Ratio FY1</th>
      <th>Price Earning Ratio FY2</th>
      <th>Price Earning Raiot LFY</th>
      </tr>
    </thead>

        <tbody>

      <tr>
        <td><%= @company.pr01 %></td>
        <td><%= @company.pr02 %></td>
        <td><%= @company.pr03 %></td>
        <td><%= @company.pr04 %></td>
        <td><%= @company.pr13 %></td>
        <td><%= @company.pr26 %></td>
        <td><%= @company.pr39 %></td>
        <td><%= @company.pr52 %></td>
        <td><%= @company.pr_year_to_date %></td>
        <td><%= @company.price_current %></td>
        <td><%= @company.warranted_price %></td>
        <td><%= @company.per_FY1 %></td>
        <td><%= @company.per_FY2 %></td>
        <td><%= @company.per_LFY %></td>
      </tr>
    </tbody>
  </table>

  <br>
  <br>

  <div id="chart" align="center">
    <%= image_tag(@line_chart) %>
  </div>

  <br>
  <br>

  <div id="analysis">
    <h3>This is our analysis.</h3>
    <b> Stock Type: </b><%= @stock_type %>
  </div>

</div>

<%= link_to 'Back', companies_path %>
<br>
<br>
<br>

app/views/home/home.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato">
<style>

body {
    background-image: url("http://cdn.pcwallart.com/images/manhattan-skyline-black-and-white-wallpaper-3.jpg");
    background-repeat: no-repeat;
    background-position: right top;
    margin-right: 200px;
    font-family: 'Lato', serif;
    font-size: 48px;

}

#id{
  margin-left: 100px;
  text-align: center;
  font-size: 200px;
}

.button {
    background-color: #000000; /* Green */
    border: none;
    color: white;
    padding: 16px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
    cursor: pointer;
}

.button5:hover {
    background-color: #555555;
    color: white;
}


</style>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("#name").fadeIn(3000);
});
</script>


</head>

<body>
<p>

<div id="name" style="width:500px;height:80px;display:none;background-color:none;">
  <h1 align="center">
  FOOBAR RESEARCH PLATFORM
  </h1>
</div>

</p>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResearchPlatform</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="top-bar" data-topbar>
  <section class="top-bar-section">
    <ul class="nav nav-pills">
      <li><%= link_to "Home", home_path %></li>
      <li><%= link_to "Search", companies_path %></li>
    </ul>
  </section>
</nav>

<div id="container">
  <%= yield %>
</div>

</body>
</html>